---
# Configuration for Bugyou Plugins

- name: install needed packages for bugyou_plugins
  package: name={{ item }} state=present enablerepo=epel-testing
  with_items:
  - python-libpagure
  - bugyou_plugins
  - redis
  notify:
  - restart fedmsg-hub
  tags:
  - bugyou
  - bugyou/plugins

- name: copy bugyou plugins configuration files
  template: >
    src={{ item }}
    dest=/etc/bugyou/{{ item }}
    owner=root
    group=fedmsg
    mode=0640
  with_items:
  - bugyou_plugins.cfg
  - bugyou_services.cfg
  notify:
  - restart fedmsg-hub
  tags:
  - bugyou
  - bugyou/plugins

- name: start the bugyou-cntrl
  service: name=bugyou-cntrl state=started
  tags:
  - bugyou
  - bugyou/plugins
  when: env == "production"
