# create a new sks keyserver
- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=anitya"

- name: make the boxen be real for real
  hosts: anitya
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - { role: denyhosts, when: ansible_distribution_major_version|int != 7 }
  - nagios_client
  - hosts
  - fas_client
  - sudo
  - collectd/base
  - openvpn/client

  tasks:
  - include: "{{ tasks }}/yumrepos.yml"
  - include: "{{ tasks }}/2fa_client.yml"
  - include: "{{ tasks }}/motd.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"

- name: set up the frontend bits
  hosts: anitya-frontend
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - apache
  - anitya/fedmsg
  - anitya/frontend
  - role: collectd/fedmsg-service
    process: fedmsg-relay

  tasks:
  - name: install fedmsg-relay
    yum: pkg=fedmsg-relay state=present
  - name: and start it
    service: name=fedmsg-relay state=started

  tags:
  - anitya

  handlers:
  - include: "{{ handlers }}/restart_services.yml"

- name: set up the backend bits
  hosts: anitya-backend
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - anitya/fedmsg
  - anitya/backend

  tags:
  - anitya

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
