# create a new sks keyserver
# NOTE: should be used with --limit most of the time
# NOTE: make sure there is room/space for this server on the vmhost
# NOTE: most of these vars_path come from group_vars/gallery-web* or from hostvars

- name: make the servers
  hosts: anitya
  user: root
  gather_facts: False

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  tasks:
  - include: "{{ tasks }}/virt_instance_create.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"

- name: make the boxen be real for real
  hosts: anitya
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - { role: denyhosts, when: ansible_distribution_major_version != '7' }
  - nagios_client
  - hosts
  - fas_client
  - sudo
  - collectd/base
  - openvpn/client

  tasks:
  - include: "{{ tasks }}/yumrepos.yml"
  - include: "{{ tasks }}/2fa_client.yml"
  - include: "{{ tasks }}/motd.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"

- name: set up the frontend bits
  hosts: anitya-frontend
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  pre_tasks:
  - include: "{{ tasks }}/apache.yml"

  roles:
  - anitya/fedmsg
  - anitya/frontend
  - role: collectd/fedmsg-service
    process: fedmsg-relay

  tasks:
  - name: install fedmsg-relay
    yum: pkg=fedmsg-relay state=present
  - name: and start it
    service: name=fedmsg-relay state=started

  tags:
  - anitya

  handlers:
  - include: "{{ handlers }}/restart_services.yml"

- name: set up the backend bits
  hosts: anitya-backend
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - anitya/fedmsg
  - anitya/backend

  tags:
  - anitya

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
