- import_playbook: "/srv/web/infra/ansible/playbooks/include/happy_birthday.yml myhosts=arm-qa"

- name: Setup arm-qa hosts
  hosts: arm-qa
  user: root
  gather_facts: True
  tags:
   - arm-qa

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  pre_tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"

  roles:
  - base
  - rkhunter
  - hosts
  - fas_client
  - sudo

  tasks:
  # this is how you include other task lists
  - import_tasks: "{{ tasks_path }}/motd.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
