- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=autocloud-web:autocloud-web-stg"

- name: make the box be real
  hosts: autocloud-web:autocloud-web-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  pre_tasks:
  - include: "{{ tasks_path }}/yumrepos.yml"

  roles:
  - base
  - rkhunter
  - nagios/client
  - hosts
  - fas_client
  - collectd/base
  - mod_wsgi
  - fedmsg/base
  - sudo
  - role: openvpn/client
    when: env != "staging"

  tasks:
  - include: "{{ tasks_path }}/2fa_client.yml"
  - include: "{{ tasks_path }}/motd.yml"

  handlers:
  - include: "{{ handlers_path }}/restart_services.yml"

- name: dole out the app-specific configuration
  hosts: autocloud-web:autocloud-web-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml
  handlers:
  - include: "{{ handlers_path }}/restart_services.yml"

  roles:
  - autocloud/frontend
