# create a new backup server system
# NOTE: should be used with --limit most of the time
# NOTE: make sure there is room/space for this instance on the buildvmhost
# NOTE: most of these vars_path come from group_vars/backup_server or from hostvars

- name: make backup server system
  hosts: backup01.phx2.fedoraproject.org
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios_client
  - hosts
  - fas_client
  - sudo
  - collectd/base
  - { role: nfs/client,
      mnt_dir: '/fedora_backups',
      nfs_mount_opts: "rw,hard,bg,intr,noatime,nodev,nosuid,nfsvers=4",
      nfs_src_dir: 'fedora_backups' }
  - openvpn/client

  tasks:
  - include: "{{ tasks_path }}/yumrepos.yml"
  - include: "{{ tasks_path }}/2fa_client.yml"
  - include: "{{ tasks_path }}/motd.yml"
  - include: "{{ tasks_path }}/rdiff_backup_server.yml"

  handlers:
  - include: "{{ handlers_path }}/restart_services.yml"
