# create a new badges-web server
# NOTE: should be used with --limit most of the time
# NOTE: make sure there is room/space for this server on the vmhost
# NOTE: most of these vars_path come from group_vars/badges-web* or from hostvars

- import_playbook: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=badges-web:badges-web-stg"

- name: make the box be real
  hosts: badges-web:badges-web-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios_client
  - hosts
  - fas_client
  - collectd/base
  - badges/frontend
  - fedmsg/base
  - rsyncd
  - sudo
  - { role: openvpn/client,
      when: env != "staging" }
  - mod_wsgi
  - role: collectd/web-service
    site: frontpage
    url: "http://localhost/"
    interval: 10
  - role: collectd/web-service
    site: leaderboard
    url: "http://localhost/leaderboard"
    interval: 10

  tasks:
  - include_tasks: "{{ tasks_path }}/yumrepos.yml"
  - include_tasks: "{{ tasks_path }}/2fa_client.yml"
  - include_tasks: "{{ tasks_path }}/motd.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
