- import_playbook: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=batcave"

- name: make the box be real
  hosts: batcave
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios_client
  - hosts
  - fas_client
  - ansible-server
  - sudo
  - collectd/base
  - git/hooks
  - cgit/base
  - cgit/clean_lock_cron
  - cgit/make_pkgs_list
  - rsyncd
  - apache
  - httpd/mod_ssl
  - role: httpd/certificate
    certname: "{{wildcard_cert_name}}"
    SSLCertificateChainFile: "{{wildcard_int_file}}"
  - openvpn/client
  - batcave
  - role: repospanner/server
    node: batcave01
    region: ansible
    spawn_repospanner_node: false

  - { role: nfs/client, when: inventory_hostname.startswith('batcave'), mnt_dir: '/srv/web/pub',  nfs_src_dir: 'fedora_ftp/fedora.redhat.com/pub' }
  - { role: nfs/client, when: inventory_hostname.startswith('batcave01'), mnt_dir: '/mnt/fedora/app',  nfs_src_dir: 'fedora_app/app' }

  pre_tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"

  tasks:
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
