- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=darkserver-web:darkserver-web-stg"

- name: make the box be real
  hosts: darkserver-web:darkserver-web-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  pre_tasks:

  - yum: name=libsemanage-python state=present
  - name: "Set SElinux booleans"
    seboolean: name=httpd_can_network_connect_db state=yes persistent=yes

  roles:
  - base
  - collectd/base
  - fas_client
  - hosts
  - nagios_client
  - rkhunter
  - rsyncd
  - sudo
  - { role: openvpn/client, when: env != "staging" }

  - role: apache
  - darkserver/web

  tasks:
  - include: "{{ tasks_path }}/yumrepos.yml"
  - include: "{{ tasks_path }}/2fa_client.yml"
  - include: "{{ tasks_path }}/motd.yml"

  handlers:
  - include: "{{ handlers_path }}/restart_services.yml"

