- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=darkserver:darkserver-stg"

- name: make the box be real
  hosts: darkserver:darkserver-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  pre_tasks:

  - yum: name=libsemanage-python state=present
  - name: "Set SElinux booleans"
    seboolean: name=httpd_can_network_connect_db state=yes persistent=yes

  roles:
  - base
  - collectd/base
  - fas_client
  - rkhunter
  - hosts
  - nagios/client
  - rsyncd
  - sudo
  - { role: openvpn/client, when: env != "staging" }

  - role: apache

  - darkserver

  tasks:
  - include: "{{ tasks }}/yumrepos.yml"
  - include: "{{ tasks }}/2fa_client.yml"
  - include: "{{ tasks }}/motd.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
