# create a new hotness server
# NOTE: should be used with --limit most of the time
# NOTE: make sure there is room/space for this server on the vmhost
# NOTE: most of these vars_path come from group_vars/mirrorlist or from hostvars

- include_playbook: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=hotness:hotness-stg"

- name: dole out the generic configuration
  hosts: hotness:hotness-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios_client
  - collectd/base
  - hosts
  - fas_client
  - sudo
  - role: keytab/service
    service: hotness
    owner_user: fedmsg
  # The proxies don't actually need to talk to these hosts so we won't bother
  # putting them on the vpn.
  #- { role: openvpn/client,
  #    when: env != "staging" }

  tasks:
  - include_tasks: "{{ tasks_path }}/yumrepos.yml"
  - include_tasks: "{{ tasks_path }}/2fa_client.yml"
  - include_tasks: "{{ tasks_path }}/motd.yml"

  handlers:
  - include_tasks: "{{ handlers_path }}/restart_services.yml"

- name: set up fedmsg basics
  hosts: hotness:hotness-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - fedmsg/base

  handlers:
  - include_tasks: "{{ handlers_path }}/restart_services.yml"

- name: dole out the service-specific config
  hosts: hotness:hotness-stg
  user: root
  gather_facts: True

  roles:
  - fedmsg/hub
  - hotness
  - role: collectd/fedmsg-service
    process: fedmsg-hub

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  handlers:
  - include_tasks: "{{ handlers_path }}/restart_services.yml"
