# create a new infinote server
- import_playbook: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=infinote"

- name: make the boxen be real for real
  hosts: infinote
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios_client
  - hosts
  - fas_client
  - sudo
  - collectd/base
  - openvpn/client
  - cgit/base
  - cgit/clean_lock_cron
  - cgit/make_pkgs_list
  - git/server
  - role: apache
  - role: httpd/mod_ssl
  - infinote
  - role: letsencrypt
    site_name: 'infinote.fedoraproject.org'
    certbot_addhost: 'infinote.fedoraproject.org'

  pre_tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"

  tasks:
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
