- import_playbook: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=pagure:pagure-stg"

- name: make the boxen be real for real
  hosts: pagure:pagure-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - nagios_client
  - hosts
  - fas_client
  - sudo
  - collectd/base
  - openvpn/client
  - postgresql_server

  tasks:
  - import_tasks: "{{ tasks_path }}/yumrepos.yml"
  - import_tasks: "{{ tasks_path }}/2fa_client.yml"
  - import_tasks: "{{ tasks_path }}/motd.yml"

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

- name: deploy pagure itself
  hosts: pagure:pagure-stg
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - "{{ vars_path }}/{{ ansible_distribution }}.yml"

  pre_tasks:
  - name: install fedmsg-relay
    package: name=fedmsg-relay state=present
    tags:
    - pagure
    - pagure/fedmsg
  - name: and start it
    service: name=fedmsg-relay state=started
    tags:
    - pagure
    - pagure/fedmsg

  roles:
  - pagure/frontend
  - pagure/fedmsg

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"
