# provision a new sign server.
# NOTE: this assumes the boxes are already up and are accessible
# NOTE: most of these vars_path come from group_vars/sign or from hostvars
#
# FURTHER NOTE: some of These machines run day to day with sshd disabled/off.
# Access is via management interface only. This playbook does initial setup.
# Please check with rel-eng before doing anything here.

- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=sign-bridge"

- name: configure sign bridge server
  hosts: sign-bridge
  user: root
  gather_facts: true

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - hosts
  - fas_client
  - sudo
  - role: keytab/service
    service: sigul
  - sigul/bridge

  tasks:
  - include: "{{ tasks }}/motd.yml"
  - include: "{{ tasks }}/yumrepos.yml"
  - include: "{{ tasks }}/2fa_client.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
