# create a new sundries server
#
# These servers run a number of smaller apps that don't merit their own instances. 
#

- name: make sundries server
  hosts: sundries;sundries-stg
  user: root
  gather_facts: False

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  tasks:
  - include: "{{ tasks }}/virt_instance_create.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"

- name: make the box be real
  hosts: sundries;sundries-stg
  user: root
  gather_facts: True

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - denyhosts
  - nagios_client
  - hosts
  - fas_client
  - collectd/base
  - apache
  - geoip
  - geoip-city-wsgi/app
  - role: koji_reminder
    when: master_sundries_node
  - role: easyfix/gather
    when: master_sundries_node
  - role: fedora_owner_change
    when: master_sundries_node and env != "staging"
  - rsyncd
  - freemedia
  - sudo
  - pager_server
  - { role: openvpn/client,
      when: env != "staging" }
  - { role: review-stats/build
    , when: env == "staging"
    }
  - { role: zanata
    , when: env == "staging"
    }
  - { role: fedora-web/build
    , when: env == "staging"
    }

  tasks:
  - include: "{{ tasks }}/yumrepos.yml"
  - include: "{{ tasks }}/2fa_client.yml"
  - include: "{{ tasks }}/motd.yml"
  - include: "{{ tasks }}/mod_wsgi.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
