# create a new sundries server
#
# These servers run a number of smaller apps that don't merit their own instances. 
#

- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=sundries:sundries-stg"

- name: make the box be real
  hosts: sundries;sundries-stg
  user: root
  gather_facts: True

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - rkhunter
  - denyhosts
  - nagios_client
  - hosts
  - fas_client
  - collectd/base
  - apache
  - geoip
  - geoip-city-wsgi/app
  - role: koji_reminder
    when: master_sundries_node
  - role: easyfix/gather
    when: master_sundries_node
  - role: fedora_owner_change
    when: master_sundries_node and env != "staging"
  - rsyncd
  - freemedia
  - sudo
  - pager_server
  - { role: openvpn/client,
      when: env != "staging" }
  - role: review-stats/build
    when: master_sundries_node
  - role: zanata
    when: master_sundries_node
  - role: fedora-web/build
    when: master_sundries_node
  - role: fedora-docs/build
    when: master_sundries_node
  - role: membership-map/build
    when: master_sundries_node

  tasks:
  - include: "{{ tasks }}/yumrepos.yml"
  - include: "{{ tasks }}/2fa_client.yml"
  - include: "{{ tasks }}/motd.yml"
  - include: "{{ tasks }}/mod_wsgi.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
