- include: "/srv/web/infra/ansible/playbooks/include/virt-create.yml myhosts=torrent"

- name: make the box be real
  hosts: torrent
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  roles:
  - base
  - hosts
  - rkhunter
  - nagios_client
  - fas_client
  - collectd/base
  - rsyncd
  - sudo
  - openvpn/client
  - torrent
  - apache

  - role: httpd/mod_ssl

  - role: httpd/certificate
    name: "{{wildcard_cert_name}}"
    SSLCertificateChainFile: "{{wildcard_int_file}}"

  - role: httpd/website
    name: torrent.fedoraproject.org
    cert_name: "{{wildcard_cert_name}}"
    sslonly: true

  tasks:
  - include: "{{ tasks_path }}/yumrepos.yml"
  - include: "{{ tasks_path }}/2fa_client.yml"
  - include: "{{ tasks_path }}/motd.yml"

  handlers:
  - include: "{{ handlers_path }}/restart_services.yml"
