# This playbook is used to rebuild staging Koschei database from
# scratch.  Useful to be ran after synchronization of staging Koji DB
# with production, which breaks Koschei - old builds from before sync
# have conflicting IDs with post-sync builds.
#
# In future, this playbook may be extended to sync content from
# production Koschei database dump, but this is not needed for now.

- name: stop koschei staging services
  hosts: koschei-backend-stg:koschei-web-stg
  user: root
  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - /srv/private/ansible/vars.yml
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml
  handlers:
  - include: "{{ handlers }}/restart_services.yml"

  tasks:
  - service: name={{ item }} state=stopped
    when: '"backend" in ansible_hostname'
    with_items:
    - koschei-resolver
    - koschei-scheduler
    - koschei-watcher
    - koschei-polling
  - service: name=httpd state=stopped
    when: '"web" in ansible_hostname'


- name: drop and re-create koschei staging database
  hosts: pgbdr01.stg.phx2.fedoraproject.org
  user: root
  become: yes
  become_user: postgres
  become_method: sudo

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - /srv/private/ansible/vars.yml
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml
  handlers:
  - include: "{{ handlers }}/restart_services.yml"

  tasks:
  - command: dropdb koschei
  - command: createdb -O koscheiadmin koschei


- name: import koschei staging database schema
  hosts: koschei-backend-stg
  user: root
  become: yes
  become_user: koschei
  become_method: sudo

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - /srv/private/ansible/vars.yml
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml
  handlers:
  - include: "{{ handlers }}/restart_services.yml"

  tasks:
  - command: koschei-admin create-db
  - command: >
      koschei-admin create-collection f26
        --display-name 'Fedora Rawhide'
        --target f26
        --branch master
        --bugzilla-product Fedora
        --bugzilla-version rawhide
  - command: >
      koschei-admin create-group php


- name: bring koschei staging services up
  hosts: koschei-backend-stg:koschei-web-stg
  user: root
  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - /srv/private/ansible/vars.yml
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml
  handlers:
  - include: "{{ handlers }}/restart_services.yml"

  tasks:
  - service: name={{ item }} state=started
    when: '"backend" in ansible_hostname'
    with_items:
    - koschei-resolver
    - koschei-scheduler
    - koschei-watcher
    - koschei-polling
  - service: name=httpd state=started
    when: '"web" in ansible_hostname'
