---
# Install retrace-server packages
- import_tasks: install.yml
  tags: [rs, packages]

# Set up use of FAF packages
- import_tasks: usefafpkgs.yml
  when: rs_use_faf_packages|bool
  tags: [rs, use_faf_packages]

# Configure retrace-server
- import_tasks: config.yml
  tags: [rs, config]

# Check functionality of the retrace-server
- import_tasks: check.yml
  when: rs_check_health|bool
  tags: [rs, check]
