---
#
# Setup ansible-server instance
#
- name: install needed packages
  yum: pkg={{ item }} state=present
  with_items:
  - ansible
  - git
  tags:
  - packages
  - ansible-server

- name: generate default ansible config
  template: src=ansible.cfg.j2 dest=/etc/ansible/ansible.cfg owner=root group=root mode=0644
  tags:
  - ansible-server

- name: installing the phx2 dns check script
  copy: src=dns_check.py dest=/usr/local/bin/dns_check owner=root mode=0755
  tags:
  - ansible-server
#
# TODO:
#  cgit?
#  rbac-playbook?
#  zodbot notifications?
#
