---
# Cron job for the fedora-owner-change

## Install packages
- name: Install needed packages
  package: name={{ item }} state=present
  with_items:
  - python-requests
  tags:
  - packages


## Install all files
- name: Install the fedora-owner-change script
  copy: >
    src=fedora-owner-change.py dest=/usr/local/bin/fedora-owner-change.py
    owner=root group=root mode=0755
  tags:
  - files


## Install the cron job
- name: Install the fedora-owner-change cronjob
  copy: >
    src=fedora-owner-change.cron dest=/etc/cron.d/fedora-owner-change.cron
    owner=root group=root mode=0644
  tags:
  - files
