- name: Copy in the sync-spins cronjob
  copy: src=cron-sync-spins dest=/etc/cron.d/sync-spins
  tags:
  - fedora-web
  - fedora-web/spins

- name: Copy some config files for {{website}}
  copy: >
    src={{item}} dest=/etc/httpd/conf.d/{{website}}/{{item}}
    owner=root group=root mode=0644
  with_items:
  - spins.conf
  - languages.conf
  notify:
  - reload proxyhttpd
  tags:
  - fedora-web
  - fedora-web/spins
