data:
  description: Fedora 30 traditional base
  license:
    module: [MIT]
  name: platform
  profiles:
    buildroot:
      rpms: [bash, bzip2, coreutils, cpio, diffutils, fedora-release, findutils, gawk,
        grep, gzip, info, make, patch, redhat-rpm-config, rpm-build, sed, shadow-utils,
        tar, unzip, util-linux, which, xz]
    srpm-buildroot:
      rpms: [bash, fedora-release, fedpkg-minimal, gnupg2, redhat-rpm-config, rpm-build,
        shadow-utils]
  stream: f30
  summary: Fedora 30 traditional base
  context: 00000000
  version: 5
  xmd:
    mbs:
      buildrequires: {}
      commit: f30
      requires: {}
      koji_tag: module-f30-build
      mse: TRUE
document: modulemd
version: 1

