- name: add infra repo
  get_url: url=http://infrastructure.fedoraproject.org/el/infrastructure.repo dest=/etc/yum.repos.d/
  when: is_rhel is defined
  tags:
  - config

- name: install cloud-utils
  package: name=cloud-utils state=present
  tags:
  - packages

- name: growpart the second partition (/) to full size
  command: growpart /dev/vda 2
  register: growpart
  check_mode: no
  changed_when: "growpart.rc != 1"
  #failed_when: growpart.rc == 2
  ignore_errors: true

- name: reboot the box
  command: /sbin/reboot
  when: growpart.rc == 0
  ignore_errors: true

- name: wait for it to come back (should be quick)
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=10 timeout=120
  when: growpart.rc == 0

- name: resize the /dev/vda 2 fs
  command: resize2fs /dev/vda2
  when: growpart.rc == 0
