---
- name: start and enable httpd
  service: name=httpd state=started enabled=yes
  become: yes

- name: add https rule to firewalld
  firewalld: service=https state=enabled permanent=true
  notify: restart firewalld
  become: yes

- name: start and enable memcached
  service: name=memcached state=started enabled=yes
  become: yes
  when: faf_web_cache_type = "memcached"

- name: turn off selinux
  selinux: state=permissive policy=targeted
