---
# tasklist for setting up a git check script
#
# The script implements various checks (even though it is named check-perms,
# it checks more than perms), and various other roles can then use it in cron
# jobs, triggered by fedmsg, etc...

- name: install the needed packages
  yum: pkg=git state=present
  tags:
  - git
  - git/checks

- name: install the script
  copy: >
    src=check-perms.py dest=/usr/local/bin/git-check-perms
    owner=root group=root mode=0755
  tags:
  - git
  - git/checks
