---
# This role sets up the fedmsg-driven atomic ostree composer

- yum: name=fedmsg-atomic-composer state=present enablerepo=infrastructure-testing

- user: name=masher
        shell=/bin/bash
        groups="mock,fedmsg"
  register: user

- file: path=/srv/fedora-atomic/
        owner={{ user['name'] }} group={{ user['name'] }} mode=755 state=directory

- seboolean: name=rsync_client state=true persistent=true
