---
# This role sets up the fedmsg-driven atomic ostree composer

- yum: name=python2-fedmsg-atomic-composer state=present

- user: name=masher
        shell=/bin/bash
        groups="mock,ftpsync,fedmsg"
  register: user

- file: path=/srv/fedora-atomic/
        owner={{ user['name'] }} group={{ user['name'] }} mode=755 state=directory

- seboolean: name=rsync_client state=true persistent=true
