- name: install faf web celery packages
  package:
    name: "{{ faf_web_celery_packages }}"
    state: present
  tags:
  - packages

- name: install redis package
  package:
    name:
      - redis
      - python-redis
    state: present
  tags:
  - packages

- name: enable redis service
  service:
    name: redis
    state: started
    enabled: yes
  tags:
  - service

- name: enable faf-celery-worker
  service:
    name: faf-celery-worker
    state: started
    enabled: yes
  tags:
  - service

- name: enable faf-celery-beat
  service:
    name: faf-celery-beat
    state: started
    enabled: yes
  tags:
  - service
