---
# Setup a fedmsg-hub

- name: install needed packages
  package: name={{ item }} state=present
  with_items:
  - python-moksha-hub
  - python-bugzilla2fedmsg
  - python-twisted-words
  tags:
  - packages
  - bugzilla2fedmsg

- name: Copy a custom moksha systemd service file
  copy: >
     src=moksha-hub.service
     dest=/usr/lib/systemd/system/moksha-hub.service
  notify:
  - restart moksha-hub
  tags:
  - bugzilla2fedmsg

- name: Make sure a few directories exist.
  file:
    dest="{{ item }}"
    owner=fedmsg
    group=fedmsg
    mode=0750
    state=directory
  with_items:
  - /etc/moksha/
  - /usr/share/fedmsg/
  tags:
  - bugzilla2fedmsg

- name: Copy the configuration for bugzilla2fedmsg over
  template: >
    src=bugzilla2fedmsg.ini
    dest=/etc/moksha/production.ini
    owner=fedmsg
    group=fedmsg
    mode=0640
  notify:
  - restart moksha-hub
  tags:
  - bugzilla2fedmsg

- name: Copy in the certs and keys.
  copy: >
    src="{{ private }}/files/bugzilla2fedmsg/{{ item }}"
    dest="/etc/pki/fedmsg/{{ item }}"
    mode=0640 owner=fedmsg group=fedmsg
  with_items:
  - msg-client-fedora-prod.crt
  - msg-client-fedora-prod.key
  notify:
  - restart moksha-hub
  tags:
  - bugzilla2fedmsg

- name: moksha-hub service
  service: name=moksha-hub state=started enabled=yes
  tags:
  - bugzilla2fedmsg
