---
- name: generate the ODCS koji config
  template:
    src: etc/koji.conf.d/odcs.conf.j2
    dest: /etc/koji.conf.d/odcs.conf
    owner: odcs
    group: odcs
    mode: 0440
  notify:
  - restart odcs-backend
  tags:
  - odcs
  - odcs/backend
