koschei_topurl: https://koschei.stg.fedoraproject.org
# koschei database on pgbdr.stg is in inconsistent state, so we're
# using non-BDR db01.stg for now.
koschei_pgsql_hostname: db01.stg.phx2.fedoraproject.org
koschei_koji_hub: koji.stg.fedoraproject.org
koschei_kojipkgs: koji.stg.fedoraproject.org
koschei_koji_web: koji.stg.fedoraproject.org
koschei_copr_url: http://copr-fe-dev.cloud.fedoraproject.org
koschei_copr_login: "{{ koschei_copr_login_stg }}"
koschei_copr_token: "{{ koschei_copr_token_stg }}"
koschei_oidc_provider: id.stg.fedoraproject.org
koschei_bugzilla: bugzilla5.redhat.com

koschei_oidc_client_secret: "{{ koschei_oidc_client_secret_stg }}"
koschei_oidc_crypto_secret: "{{ koschei_oidc_crypto_secret_stg }}"
