---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coreos-cincinnati-config-stub
data:
  config.json: |
    {
      "version": "target-version",
      "metadata": {
        "org.fedoraproject.coreos.scheme": "checksum"
      },
      "payload": "dummy-digest"
    }
