- name: chmod_key
  file: path=/etc/lighttpd/copr-be.fedoraproject.org.pem owner=root group=root mode=0600

- name: restart copr-backend
  service: name=copr-backend state=restarted

- name: systemctl daemon-reload
  command: /usr/bin/systemctl daemon-reload

- name: restart lighttpd
  action: service name=lighttpd state=restarted
