- name: copy httpd ssl certificates (crt)
  copy: src="{{ puppet_private }}/httpd/copr-fe.fedoraproject.org.crt" dest="/etc/pki/tls/certs/" owner=root group=root mode=0600
  tags:
  - config

- name: copy httpd ssl certificates (key)
  copy: src="{{ puppet_private }}/httpd/copr-fe.fedoraproject.org.key" dest="/etc/pki/tls/private/" owner=root group=root mode=0600
  tags:
  - config

- name: copy httpd ssl certificates (CAcert)
  copy: src=DigiCertCA.crt dest="/etc/pki/tls/certs/" owner=root group=root mode=0600
  tags:
  - config
