- name: Copy over the Fedora Server CA cert
  copy: src="{{ private }}/files/fedora-ca.cert" dest=/etc/pki/httpd/fedora-server-ca.cert
        owner=root group=root mode=0644
  notify:
  - reload proxyhttpd
  tags:
  - fedora-web
  - fedora-web/registry

- name: Copy over the registry passwd
  copy: src=passwd dest=/etc/httpd/conf.d/registry.fedoraproject.org/passwd
        owner=root group=root mode=0644
  notify:
  - reload proxyhttpd
  tags:
  - fedora-web
  - fedora-web/registry
