apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: totpcgi
  name: totpcgi
spec:
  runPolicy: Serial
  source:
    dockerfile: |-
      FROM registry.access.redhat.com/rhel6
      RUN curl -o /etc/yum.repos.d/rhel6.repo https://infrastructure.fedoraproject.org/cgit/ansible.git/plain/files/common/rhel6.repo && \
          curl -o /etc/yum.repos.d/epel6.repo https://infrastructure.fedoraproject.org/cgit/ansible.git/plain/files/common/epel6.repo && \
{% if env == "staging" %}
          curl -o /etc/yum.repos.d/infra-tags-stg.repo https://infrastructure.fedoraproject.org/cgit/ansible.git/plain/files/common/rhel-infra-tags-stg.repo && \
{% endif %}
          curl -o /etc/yum.repos.d/infra-tags.repo https://infrastructure.fedoraproject.org/cgit/ansible.git/plain/files/common/rhel-infra-tags.repo

      RUN yum install -y \
          mod_auth_pgsql \
          totpcgi \
          totpcgi-provisioning \
          python-qrcode \
          httpd \
          mod_ssl \
          python-fedora \
          python-psycopg2

      RUN curl https://infrastructure.fedoraproject.org/cgit/ansible.git/plain/roles/totpcgi/files/index.cgi -o /var/www/totpcgi/index.cgi

      RUN chmod -R o+rx /var/www/totpcgi*

      EXPOSE 8080
      ENTRYPOINT bash /etc/totpcgi/start.sh
    type: Dockerfile
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: totpcgi:latest
