---
# tasklist for setting up Gitolite Fedmsg checks

- name: schedule check execution
  cron: >
    name=git-check-perms
    cron_file=ansible-git-check-perms
    minute=10
    hour=0
    weekday=3
    user=nobody
    job="MAILTO=root PATH=/usr/bin:/usr/local/bin/git-check-perms /srv/git/repositories --check=fedmsg-hook"
