apiVersion: v1
kind: ImageStream
metadata:
  name: "{{ app }}"
  labels:
    app: "{{ app }}"
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
{% if env == 'staging' %}
      name: "quay.io/factory2/{{ app }}:stage"
{% else %}
      name: "quay.io/factory2/{{ app }}:prod"
{% endif %}
    importPolicy:
      scheduled: true
