- name: Copy in the sync-labs cronjob
  copy: src=cron-sync-labs dest=/etc/cron.d/sync-labs
  tags:
  - fedora-web
  - fedora-web/labs

- name: Copy some config files for {{website}}
  copy: >
    src={{item}} dest=/etc/httpd/conf.d/{{website}}/{{item}}
    owner=root group=root mode=0644
  with_items:
  - labs.conf
  - languages.conf
  notify:
  - reload proxyhttpd
  tags:
  - fedora-web
  - fedora-web/labs
