- name: Copy in the sync-mirrors cronjob
  copy: src=cron-sync-mirrors dest=/etc/cron.d/sync-mirrors
  tags:
  - fedora-web
  - fedora-web/mirrors

- name: Copy some config files for {{website}}
  copy: >
    src={{item}} dest=/etc/httpd/conf.d/{{website}}/{{item}}
    owner=root group=root mode=0644
  with_items:
  - mirrors.conf
  notify:
  - reload proxyhttpd
  tags:
  - fedora-web
  - fedora-web/mirrors
