---
odcs_upgrade: False
odcs_force_postgres_ssl: False
odcs_pdc_insecure: False
odcs_pdc_develop: True
odcs_target_dir: /srv/odcs
odcs_target_dir_url: http://{{ inventory_hostname }}/composes
odcs_allowed_clients_groups: {"sysadmin-mbs": {}, "sysadmin-osbs": {}}
odcs_allowed_clients_users: {"osbs@service": {}}
odcs_admin_groups: ["sysadmin-mbs"]
odcs_admin_users: []
odcs_raw_config_urls: {}
odcs_pungi_runroot_enabled: False
odcs_pungi_parent_runroot_channel: compose
odcs_pungi_parent_runroot_packages: ["pungi"]
odcs_pungi_parent_runroot_mounts: []
odcs_pungi_parent_runroot_weight: 3.5
odcs_pungi_parent_runroot_tag: f27-build
odcs_pungi_parent_runroot_arch: x86_64
odcs_pungi_runroot_target_dir: /mnt/koji/compose/odcs
odcs_pungi_runroot_target_dir_url: http://kojipkgs.fedoraproject.org/compose/odcs
odcs_messaging_backend: fedmsg
odcs_messaging_certificate: "/THIS/FILE/PROBABLY/DOESNT/EXIST"
odcs_messaging_private_key: "/THIS/FILE/PROBABLY/DOESNT/EXIST"
odcs_messaging_broker_urls: []
odcs_messaging_ca_cert: /etc/ssl/certs/ca-bundle.trust.crt
odcs_allowed_clients: {"users": [], "groups": []}
odcs_admins: {"users": [], "groups": []}
odcs_allowed_source_types: ["tag", "module"]
odcs_allowed_flags: null
odcs_allowed_arches: ['aarch64', 'armv7hl', 'i686', 'ppc64le', 'x86_64', 's390x']
odcs_allowed_results: null
odcs_allowed_sources: null
odcs_arches: ["x86_64"]
odcs_sigkeys: []
odcs_messaging_producer_broker_urls: []
odcs_messaging_consumer_broker_urls: []

