---
- name: install packages
  yum: name={{ item }} state=present
  with_items:
  - bind
  - unzip
  - git
  tags:
  - packages

- name: create directories
  file: path=/var/named/chroot/{{ item }} state=directory owner=named group=named mode=0755
  with_items:
  - ""
  - "etc"
  - "etc/named"
  - "cache"
  - "dev"
  - "log"
  - "var"
  - "usr"
  - "usr/lib"
  - "usr/lib/bind"
  - "var/named"
  - "var/run"
  - "var/run/named"
  - "master"

- name: create chroot random
  command: /bin/mknod /var/named/chroot/dev/random c 1 8
  args:
    creates: /var/named/chroot/dev/random

- name: create chroot null
  command: /bin/mknod /var/named/chroot/dev/null c 1 3
  args:
    creates: /var/named/chroot/dev/null

- name: create chroot zero
  command: /bin/mknod /var/named/chroot/dev/zero c 1 5
  args:
    creates: /var/named/chroot/dev/zero

- name: copy rndc config
  copy: src=rndc.conf dest=/etc/rndc.conf
  notify:
  - restart named
  tags:
  - config

- name: copy rndc key
  copy: src={{ private }}/files/dns/rndc.key dest=/etc/rndc.key
  notify:
  - restart named
  tags:
  - config

- name: copy named cache
  copy: src=named.ca dest=/var/named/chroot/cache/named.ca
  notify:
  - restart named
  tags:
  - config

- name: copy named sysconfig
  copy: src=named dest=/etc/sysconfig/named mode=0644 owner=root group=root
  notify:
  - restart named
  tags:
  - config

- name: copy GeoIP.sh
  copy: src=GeoIP.sh dest=/var/named/chroot/GeoIP.sh mode=0755
  notify:
  - restart named
  tags:
  - config

- name: create GeoIP acl
  command: /var/named/chroot/GeoIP.sh
  notify:
  - restart named

- name: copy update-dns
  copy: src=update-dns dest=/usr/local/bin/update-dns mode=0755
  notify:
  - restart named
  tags:
  - config

- name: copy zones
  copy: src=zones.conf dest=/var/named/chroot/etc/zones.conf owner=root group=root mode=0644
  notify:
  - restart named
  tags:
  - config

- name: copy named config
  copy: src=named.conf dest=/var/named/chroot/etc/named.conf mode=0644 owner=root group=root
  notify:
  - restart named
  tags:
  - config

- name: update dns
  command: /usr/local/bin/update-dns
  notify:
  - restart named
  tags:
  - config

- name: named service
  service: name=named state=started enabled=yes
