---
OS_AUTH_URL: "{{ copr_nova_auth_url }}"

OS_TENANT_ID: "{{ copr_nova_tenant_id }}"
OS_TENANT_NAME: "{{ copr_nova_tenant_name }}"

OS_USERNAME: "{{ copr_nova_username }}"

# remove default values after transition to the new cloud is finished
OS_PASSWORD_OLD: "{{ copr_nova_password|default('variable OS_PASSWORD_OLD is undefined') }}"
OS_PASSWORD: "{{ copr_password|default('variable OS_PASSWORD is undefined')}}"

flavor_name: "{{ copr_builder_flavor_name }}"
network_name: "{{ copr_builder_network_name }}"
key_name: "{{ copr_builder_key_name }}"
security_groups: "{{ copr_builder_security_groups }}"
