- name: Set up those proxy certificates.  Good gravy..
  hosts: proxies-stg:proxies
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

  roles:

  - role: httpd/mod_ssl

  - role: httpd/certificate
    certname: wildcard-2017.fedoraproject.org
    SSLCertificateChainFile: wildcard-2017.fedoraproject.org.intermediate.cert

  - role: httpd/certificate
    certname: wildcard-2017.fedorahosted.org
    SSLCertificateChainFile: wildcard-2017.fedorahosted.org.intermediate.cert

  - role: httpd/certificate
    certname: wildcard-2017.id.fedoraproject.org
    SSLCertificateChainFile: wildcard-2017.id.fedoraproject.org.intermediate.cert

  - role: httpd/certificate
    certname: wildcard-2017.stg.fedoraproject.org
    SSLCertificateChainFile: wildcard-2017.stg.fedoraproject.org.intermediate.cert
    when: env == "staging"

  - role: httpd/certificate
    certname: wildcard-2017.app.os.stg.fedoraproject.org
    SSLCertificateChainFile: wildcard-2017.app.os.stg.fedoraproject.org.intermediate.cert
    when: env == "staging"
    tags:
    - app.os.fedoraproject.org

  - role: httpd/certificate
    certname: wildcard-2017.app.os.fedoraproject.org
    SSLCertificateChainFile: wildcard-2017.app.os.fedoraproject.org.intermediate.cert
    tags:
    - app.os.fedoraproject.org

  - role: httpd/certificate
    certname: fedoramagazine.org
    SSLCertificateChainFile: fedoramagazine.org.intermediate.cert

  - role: httpd/certificate
    certname: fpaste.org
    SSLCertificateChainFile: fpaste.org.intermediate.cert
    tags:
    - fpaste.org

  - role: httpd/certificate
    certname: jenkins.fedorainfracloud.org
    SSLCertificateChainFile: jenkins.fedorainfracloud.org.intermediate.cert

  - role: httpd/certificate
    certname: getfedora.org
    SSLCertificateChainFile: getfedora.org.intermediate.cert

  - role: httpd/certificate
    certname: flocktofedora.org
    SSLCertificateChainFile: flocktofedora.org.intermediate.cert

  - role: httpd/certificate
    certname: qa.stg.fedoraproject.org
    SSLCertificateChainFile: qa.stg.fedoraproject.org.intermediate.cert
    when: env == "staging"

  - role: httpd/certificate
    certname: qa.fedoraproject.org
    SSLCertificateChainFile: qa.fedoraproject.org.intermediate.cert

  - role: httpd/certificate
    certname: secondary.koji.fedoraproject.org.letsencrypt
    SSLCertificateChainFile: secondary.koji.fedoraproject.org.letsencrypt.intermediate.crt

  - role: httpd/certificate
    certname: whatcanidoforfedora.org
    SSLCertificateChainFile: whatcanidoforfedora.org.intermediate.crt
    tags:
    - whatcanidoforfedora.org

  - role: httpd/certificate
    certname: fedoracommunity.org
    SSLCertificateChainFile: fedoracommunity.org.intermediate.cert
    tags:
    - fedoracommunity.org
