- name: Set up all the other proxy stuff -- miscellaneous
  hosts: proxies-stg:proxies
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  handlers:
  - include_tasks: "{{ handlers_path }}/restart_services.yml"

  tasks:
      # We retired this in favor of PDC
      # https://lists.fedoraproject.org/archives/list/rel-eng@lists.fedoraproject.org/thread/LOWVTF6WTS43LNPWDEISLXUELXAH5YXR/#LOWVTF6WTS43LNPWDEISLXUELXAH5YXR
      - file:
          dest=/etc/httpd/conf.d/apps.fedoraproject.org/fedora-releng-dash.conf
          state=absent
        tags: releng-dash
        notify: reload proxyhttpd

  roles:

  - role: httpd/mime-type
    website: fedoraproject.org
    mimetype: image/vnd.microsoft.icon
    extensions:
    - .ico

  - role: fedmsg/crl
    website: fedoraproject.org
    path: /fedmsg

  - role: fedmsg/gateway/slave
    stunnel_service: "websockets"
    stunnel_source_port: 9939
    stunnel_destination_port: 9938

  - role: httpd/fingerprints
    website: admin.fedoraproject.org

  - role: easyfix/proxy
    website: fedoraproject.org
    path: /easyfix

  - role: review-stats/proxy
    website: fedoraproject.org
    path: /PackageReviewStatus

  - role: membership-map/proxy
    website: fedoraproject.org
    path: /membership-map

  - role: apps-fp-o
    website: apps.fedoraproject.org
    path: /
