- name: Copy in the sync-getfedora cronjob
  copy: src=cron-sync-getfedora dest=/etc/cron.d/sync-getfedora
  tags:
  - fedora-web
  - fedora-web/getfedora

- name: Copy some config files for {{website}}
  copy: >
    src={{item}} dest=/etc/httpd/conf.d/{{website}}/{{item}}
    owner=root group=root mode=0644
  with_items:
  - getfedora.org.conf
  - languages.conf
  notify:
  - reload proxyhttpd
  tags:
  - fedora-web
  - fedora-web/getfedora
