- name: provision CoreOS Cincinnati backend
  hosts: os_masters_stg[0]
  user: root
  gather_facts: False

  vars_files:
    - /srv/web/infra/ansible/vars/global.yml
    - "/srv/private/ansible/vars.yml"
    - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml
    - /srv/web/infra/ansible/roles/openshift-apps/coreos-cincinnati/vars/{{ env }}.yml

  pre_tasks:
  - include_vars: dir=/srv/web/infra/ansible/vars/all/ ignore_files=README

  roles:
  - role: openshift/project
    app: coreos-cincinnati
    description: Fedora CoreOS Cincinnati backend
    appowners:
    - jlebon
    - lucab
    - sanja
    egress_policy_template: "{{ roles_path }}/openshift-apps/coreos-cincinnati/templates/egresspolicy.yml"

  - role: openshift/imagestream
    app: coreos-cincinnati
    imagename: fedora-coreos-cincinnati

  - role: openshift/object
    app: coreos-cincinnati
    template: buildconfig-stub.yml
    objectname: buildconfig-stub.yml

  - role: openshift/object
    app: coreos-cincinnati
    file: config-stub.yml
    objectname: config-stub.yml

  - role: openshift/object
    app: coreos-cincinnati
    template: deploymentconfig.yml
    objectname: deploymentconfig.yml

  - role: openshift/object
    app: coreos-cincinnati
    file: service.yml
    objectname: service.yml

  - role: openshift/route
    app: coreos-cincinnati
    routename: coreos-updates
    host: "updates{{ env_suffix }}.coreos.fedoraproject.org"
    serviceport: coreos-cincinnati-service
    servicename: coreos-cincinnati
