[zmq_to_amqp]
# The AMQP exchange to publish to.
exchange = "zmq.topic"
# A list of topics to filter the incoming ZMQ messages on; by default all
# messages are forwarded to AMQP.
topics = [""]
# A list of strings in the ZeroMQ socket format (e.g. "tcp://host:socket")
zmq_endpoints = [
{% if env == 'staging' %}
    "tcp://stg.fedoraproject.org:9940",
{% else %}
    "tcp://fedoraproject.org:9940",
{% endif %}
    #"tcp://release-monitoring.org:9940",
]

[verify_missing]
# The queue to setup
[verify_missing.queue]
queue = "amqp_bridge_verify_missing"
durable = true
auto_delete = false
exclusive = false
arguments = { x-message-ttl = 60000 }
# The exchanges to declare
[[verify_missing.exchanges]]
exchange = "amq.topic"
exchange_type = "topic"
durable = true
[[verify_missing.exchanges]]
exchange = "zmq.topic"
exchange_type = "topic"
durable = true
# The bindings to use for the AMQP queue
[[verify_missing.bindings]]
exchange = "zmq.topic"
queue = "amqp_bridge_verify_missing"
routing_key = "#"
[[verify_missing.bindings]]
exchange = "amq.topic"
queue = "amqp_bridge_verify_missing"
routing_key = "#"

[log_config]
version = 1
disable_existing_loggers = true
[log_config.filters.ratelimit]
"()" = "fedmsg_migration_tools.filters.RateLimiter"
rate = 120
[log_config.formatters.simple]
format = "%(asctime)s [%(name)s %(levelname)s] %(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"
[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"
[log_config.handlers.email]
class = "logging.handlers.SMTPHandler"
formatter = "simple"
filters = ["ratelimit"]
mailhost = "bastion"
fromaddr = "fedmsg-migration-tools@fedoraproject.org"
toaddrs = ["jcline@fedoraproject.org", "abompard@fedoraproject.org"]
subject = "ERROR: fedmsg-migration-tools verify-missing service ({{ env }})"
[log_config.loggers.fedmsg_migration_tools]
level = "INFO"
propagate = false
handlers = ["console"]
[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]
[log_config.loggers.fedmsg]
level = "INFO"
propagate = false
handlers = ["console"]
[log_config.root]
level = "WARNING"
handlers = ["console", "email"]
