---
trigger_joblog_file: /var/log/taskotron-trigger/jobs.csv
trigger_critpath_file: /var/lib/taskotron-trigger/critpath_whitelist
trigger_cache_dir: /var/lib/taskotron-trigger/cache
trigger_rules_template_path: /etc/taskotron/trigger_rules.yml
extra_enablerepos: ''
