---
- include: koschei.yml
  vars:
    fedora_repos:
    - updates-testing
    - msimacek-koschei
    epel_repos:
    - epel-testing
    - msimacek-koschei
    koschei_backend_hosts: koschei-backend-stg
    koschei_web_hosts: koschei-web-stg
