- name: Copy some config files for {{website}}
  template: >
    src={{item}} dest=/etc/httpd/conf.d/{{website}}/{{item}}
    owner=root group=root mode=0644
  with_items:
  - fedoramagazine-web.conf
  notify:
  - restart httpd
  tags:
  - fedora-web
  - fedora-web/magazine
