- name: Copy in the sync-start cronjob
  copy: src=cron-sync-start dest=/etc/cron.d/sync-start
  tags:
  - fedora-web
  - fedora-web/start

- name: Copy some config files for {{website}}
  copy: >
    src={{item}} dest=/etc/httpd/conf.d/{{website}}/{{item}}
    owner=root group=root mode=0644
  with_items:
  - start-web.conf
  - languages.conf
  notify:
  - reload proxyhttpd
  tags:
  - fedora-web
  - fedora-web/start
