---
#
# This task sets up /etc/hosts on a machine.
#
# This should only be used in rare cases
#

#
# This will move a /etc/hosts in place if it's setup in files for that host/domain
# Note that if it's not set it will just skip this play and do nothing.
#
- name: setup /etc/hosts for some clients
  copy: src={{ item }} dest=/etc/hosts
  with_first_found:
  - files:
    - "{{ inventory_hostname }}-hosts"
    - "{{ ansible_hostname }}-hosts"
    - "{{ host_group }}-hosts"
    - "{{ ansible_domain }}-hosts"
    - "{{ datacenter }}-hosts"
    - "base"
    skip: true
  tags:
  - config
  - hosts
