# setup a transient fedora instance
# optionally can take --extra-vars="hostbase=hostnamebase root_auth_users='user1 user2 user3'"

- name: check/create instance
  hosts: lockbox01.phx2.fedoraproject.org
  user: root
  gather_facts: False

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
  vars:
  - keypair: fedora-admin-20130801
  - image: "{{ el7_qcow_id }}"
  - instance_type: m1.small
  - security_group: default

  tasks:
  - include: "{{ tasks }}/transient_cloud.yml"

- name: provision instance
  hosts: tmp_just_created
  gather_facts: True
  user: fedora
  sudo: True

  vars_files: 
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  tasks:
  - name: install cloud-utils
    yum: pkg=cloud-utils state=present

  - name: growpart /dev/vda1 partition (/) to full size
    action: command growpart /dev/vda 1
    register: growpart
    always_run: true
    changed_when: "growpart.rc != 1"
    failed_when: growpart.rc == 2

  - name: resize the /dev/vda 1 fs
    action: command xfs_growfs /dev/vda1
    when: growpart.rc == 0

#  - name: put the mbr back - b/c the resize breaks booting otherwise
#    action: shell cat /usr/share/syslinux/mbr.bin > /dev/vda
#    when: growpart.rc == 0


  - include: "{{ tasks }}/cloud_setup_basic.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"
