---
#
# Use this playbook to run over all the playbooks that have fedmsg.d in them.
#
# Call it with -t fedmsgdupdate to only run that one play.
#
- include_playbook: /srv/web/infra/ansible/playbooks/hosts/copr-be.cloud.fedoraproject.org.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/ask.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/bodhi.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/badges-backend.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/badges-web.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/busgateway.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/elections.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/fedocal.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/gallery.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/keyserver.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/koji-hub.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/mailman.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/notifs-backend.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/notifs-web.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/nuancier.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/packages.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/releng.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/tagger.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/wiki.yml
- include_playbook: /srv/web/infra/ansible/playbooks/groups/value.yml
