# Run `fasClient` on all hosts, N hosts at a time
#
# We exclude builders, persistent-cloud, jenkins-master and jenkins-slave as they don't have fasclient
#

- name: run fasClient -a to make email aliases on bastion
  hosts: bastion01.phx2.fedoraproject.org:bastion02.phx2.fedoraproject.org
  user: root
  gather_facts: False

  tasks:
  - name: actually run fasClient -a
    command: fasClient -a
    ignore_errors: true
    when: inventory_hostname_short.startswith('bastion0')

- name: run fasClient on people and pkgs first as these are the ones most people want updated
  hosts: people02.fedoraproject.org:pkgs02.phx2.fedoraproject.org
  user: root
  gather_facts: False

  tasks:
  - name: actually run fasClient -i
    command: fasClient -i
    ignore_errors: true

- name: run fasClient -i on the rest of hosts which only affects sysadmins
  hosts: all:!builders:!*cloud*:!*composer*:!people*:!pkgs02*:!*.stg.*:!twisted*:!*.fedorainfracloud.org:!bkernel*:!autosign*:!*.app.os.fedoraproject.org:!*.app.os.stg.fedoraproject.org:
  user: root
  gather_facts: False

  tasks:
  - name: actually run fasClient -i
    command: fasClient -i
    ignore_errors: true
