---
galaxy_info:
  author: "ABRT team"
  company: Red Hat
  license: BSD
  min_ansible_version: 1.8
  platforms:
   - name: EL
     versions:
      - 7
      - 6
   - name: Fedora
     versions:
      - 26
      - 27
      - 28
  categories:
   - web
dependencies: []
