---
galaxy_info:
  author: "ABRT team"
  company: Red Hat
  license: BSD
  min_ansible_version: 2.5
  platforms:
   - name: EL
     versions:
      - 8
   - name: Fedora
     versions:
      - 29
      - 30
  categories:
   - web
dependencies: []
