#
# A playbook to get all the rpms installed on a set of systems. 
# 

- name: Get installed packages
  hosts: builders:releng-compose:data-analysis01.phx2.fedoraproject.org
  gather_facts: true
  user: root

  tasks:

  - name: RPM_output
    shell: "/usr/bin/rpm -qa"
    register: rpm_output
    args:
      warn: false # set warn=false to prevent warning


  - debug: var=rpm_output.stdout_lines
#    when: rpm_output is defined and rpm_output.results|length > 0

