clean_up_on_failure: True
delete_images_on_failure: True

aws_util_username: ec2-user
aws_test_username: fedora
aws_util_volume_size: 6
aws_test_volume_size: 6
# access_id and secret_key are in private vars
aws_iam_profile: "arn:aws:iam::013116697141:user/oddshocks"
aws_test: "/bin/true"
