clean_up_on_failure: True
delete_image_on_failure: True

aws_util_username: ec2-user
aws_test_username: fedora
# access_id and secret_key are in private vars
aws_iam_profile: "arn:aws:iam::013116697141:user/oddshocks"
aws_test: "/bin/true"
