# This is a basic playbook

- name: dole out the generic configuration
  hosts: data-analysis01.phx2.fedoraproject.org
  user: root
  gather_facts: True

  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  pre_tasks:
  - include: "{{ tasks }}/yumrepos.yml"

  roles:
  - base
  - rkhunter
  - hosts
  - fas_client
  - nagios/client
  - collectd/base
  - sudo
  - role: keytab/service
    owner_user: apache
    owner_group: apache
    service: HTTP
    host: "data-analysis.fedoraproject.org"
    when: env == "production"
  - awstats
  - web-data-analysis

  tasks:
  - include: "{{ tasks }}/2fa_client.yml"
  - include: "{{ tasks }}/motd.yml"

  handlers:
  - include: "{{ handlers }}/restart_services.yml"

- name: dole out the service-specific config
  hosts: data-analysis01.phx2.fedoraproject.org
  user: root
  gather_facts: True
  vars_files:
   - /srv/web/infra/ansible/vars/global.yml
   - "/srv/private/ansible/vars.yml"
   - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml
  handlers:
  - include: "{{ handlers }}/restart_services.yml"

  roles:
   - role: nfs/client
     mnt_dir: '/mnt/fedora_stats'
     nfs_mount_opts: "rw,hard,bg,intr,noatime,nodev,nosuid,nfsvers=4"
     nfs_src_dir: 'fedora_stats'
   - geoip

  tasks:
   - name: install needed packages
     yum: pkg={{ item }} state=present
     with_items:
       - httpd
       - httpd-tools
       - mod_ssl
       - rsync
       - openssh-clients
       - emacs-nox
       - emacs-git
       - git
       - bc
       - python-geoip-geolite2
       - php-pdo
       - php-gd
       - php-xml
       - php-mysql
       - php-mbstring
       - php
       - mariadb
       - mariadb-server
       - php-pecl-geoip
       - gnuplot
       - htmldoc

   - name: setup mysql items
     file: path=/srv/mysql state=directory mode=0770 owner=mysql group=mysql setype=mysqld_db_t

   - name: semanage mysql tree
     command: /usr/sbin/semanage fcontext -a -t mysqld_db_t "/srv/mysql(/.*)?"


##
